[target.xtensa-esp32-none-elf]
image = "reitermarkus/cross:xtensa-esp32-none-elf"
env = { volumes = ["IDF_PATH", "IDF_TOOLS_PATH"] }

[target.xtensa-esp32-espidf]
image = "reitermarkus/cross:xtensa-esp32-espidf"
env = { volumes = ["IDF_PATH", "IDF_TOOLS_PATH"] }



